include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.mocks.dart"
linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    require_trailing_commas: true
    prefer_single_quotes: true
    sort_pub_dependencies: true

